package(
    default_visibility = ["//visibility:private"],
)

cc_library(
    name = "oov_token_behavior",
    hdrs = ["oov_token_behavior.h"],
    visibility = ["//:internal_users"],
    deps = ["@com_google_absl//absl/log:absl_check"],
)
