name: Gematria CI

on: [push, repository_dispatch, pull_request]

jobs:
  check-python-formatting:
    name: Python Formatting Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install pyink
        run: pip3 install pyink==23.5.0
      - name: Check python formatting
        run: pyink --check --diff .
  check-cpp-formatting:
    name: C++ Formatting Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check c++ formatting
      uses: jidicula/clang-format-action@v4.11.0
      with:
        clang-format-version: '16'
        check-path: 'src'
  check-bazel-formatting:
    name: Bazel Formatting Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: thompsonja/bazel-buildifier@v0.4.0
      with:
        buildifier_version: v6.1.2
